language: javascript

script:
  - cd src
  - npm install
  - cd ..
  

services:
  - docker


before_deploy:
 - mkdir -p deploy
 - docker build -t giraffeb/docker-test .
 - docker save -o deploy/docker-test.tar giraffeb/test

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: giraffeb-bucket # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true

    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: giraffeb/docker-test
      branch: master

#   - provider: codedeploy # AWS CodeDeploy를 의미
#     access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
#     secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
#     bucket: giraffeb-bucket # AWS CodeDeploy가 다운로드 받은 버킷
#     key: makingboard.tar # 해당 버킷에 저장되어 있는 파일 이름
#     bundle_type: tar # 버킷에 저장되어 있는 파일의 확장자
#     application: making_board # AWS 배포 애플리케이션
#     deployment_group: personal_project # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
#     region: ap-northeast-2
#     wait-until-deployed: true
#     on:
#       repo: giraffeb/makingboad
#       branch: master

notifications:
  email:
    recipients:
      - soulgoon@gmail.com